### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by Akshay-shiva** [itspacchu/jntu-scraper#1]
Bro write a proper readme file

**Comment by pacsui** [comment]
yeah ill work on it after finishing some stuff

**Comment by pacsui** [comment]
> 
> 
> yeah ill work on it after finishing some stuff

check it out now @Akshay-shiva it should be more friendlier if i can say

**Comment by Akshay-shiva** [comment]
Great! As of now connection time  out error but  Found a bug (Today 4-2 results announced. )
Roll Number invalid if last two places are combination of a constant and Variable

**Comment by Akshay-shiva** [comment]
Great!
