### ISSUE TITLE
Roll No Invalid 

### ISSUE THREAD

**Issue by Akshay-shiva** [itspacchu/jntu-scraper#2]
Found a bug (Today 4-2 results announced , you may check it yourself)
Roll Number invalid if last two literals  in the string are combination of a constant and Variable 
> Roll-Number not Valid

Update : Found that if last literal is below H it outputs value for the rest it is a bug

**Comment by pacsui** [comment]
I think its because of the RollNoValidator function .. maybe try disabling it like not checking for rollnumber?

**Comment by pacsui** [comment]
I don't think a rollno can have something like ```18AG1A04HH``` so last literal can't be H it can only lie between 0-9
```18AG1A04H0  -> 18AG1A04H9```

just tested the 4-2 results and it does seem to work

![image](https://user-images.githubusercontent.com/37984032/129202999-b1f43f80-b3f1-4a88-bf70-8e196e3a627d.png)

idk anyone from 4-2 with 4HX in my college but it isnt throwing any RollNo invalid error for me.
maybe send a screenshot /code/rollno which is throwing that error?

**Comment by Akshay-shiva** [comment]
No, we do actually have roll numbers
Keep these roll numbers private , only check for the testing's sake - Try
17BD1A053H  you will get but you won't get for 17BD1A053J till 3V
Same goes for 2J till 2Z

python3 jnturesultscrap.py 17BD1A055H 1463
>> {'user': ['17BD1A055H', 'S MANASI', 'S GANESH RAO', 'BD'], 'result':
[{'SUB_CODE': '13805', 'SUB_NAME': 'MAJOR PROJECT', 'INTERNAL': '24',
'EXTERNAL': '72', 'TOTAL': '96', 'GRADE': 'O', 'CREDIT': '15'},
{'SUB_CODE': '138EK', 'SUB_NAME': 'REAL TIME SYSTEMS', 'INTERNAL': '25',
'EXTERNAL': '30', 'TOTAL': '55', 'GRADE': 'B', 'CREDIT': '3'}, {'SUB_CODE':
'138FH', 'SUB_NAME': 'WEB SERVICES AND SERVICE ORIENTED ARCHITECTURE',
'INTERNAL': '25', 'EXTERNAL': '36', 'TOTAL': '61', 'GRADE': 'B+', 'CREDIT':
'3'}, {'SUB_CODE': '138GY', 'SUB_NAME': 'SENSORS AND TRANSDUCERS',
'INTERNAL': '25', 'EXTERNAL': '50', 'TOTAL': '75', 'GRADE': 'A', 'CREDIT':
'3'}], 'sgpa': 8.88}


python3 jnturesultscrap.py 17BD1A055J 1463
>> Roll-Number not Valid

**Comment by Akshay-shiva** [comment]
send me your working mail. I'll post the screenshots

**Comment by Akshay-shiva** [comment]
python3 jnturesultscrap.py 17BD1A05**5J** 1463 
> Roll-Number not Valid

python3 jnturesultscrap.py 17BD1A05**5L** 1463 
> Roll-Number not Valid


 python3 jnturesultscrap.py 17BD1A05**5H** 1463 
> {'user': ['17BD1A055H', 'S MANASI', 'S GANESH RAO', 'BD'], 'result': [{'SUB_CODE': '13805', 'SUB_NAME': 'MAJOR PROJECT', 'INTERNAL': '24', 'EXTERNAL': '72', 'TOTAL': '96', 'GRADE': 'O', 'CREDIT': '15'}, {'SUB_CODE': '138EK', 'SUB_NAME': 'REAL TIME SYSTEMS', 'INTERNAL': '25', 'EXTERNAL': '30', 'TOTAL': '55', 'GRADE': 'B', 'CREDIT': '3'}, {'SUB_CODE': '138FH', 'SUB_NAME': 'WEB SERVICES AND SERVICE ORIENTED ARCHITECTURE', 'INTERNAL': '25', 'EXTERNAL': '36', 'TOTAL': '61', 'GRADE': 'B+', 'CREDIT': '3'}, {'SUB_CODE': '138GY', 'SUB_NAME': 'SENSORS AND TRANSDUCERS', 'INTERNAL': '25', 'EXTERNAL': '50', 'TOTAL': '75', 'GRADE': 'A', 'CREDIT': '3'}], 'sgpa': 8.88}


python3 jnturesultscrap.py 17BD1A05**5A** 1463 
> {'user': ['17BD1A055A', 'PALREDDY SRIYA REDDY', 'PALREDDY KARUNAKAR REDDY', 'BD'], 'result': [{'SUB_CODE': '13805', 'SUB_NAME': 'MAJOR PROJECT', 'INTERNAL': '24', 'EXTERNAL': '72', 'TOTAL': '96', 'GRADE': 'O', 'CREDIT': '15'}, {'SUB_CODE': '138EK', 'SUB_NAME': 'REAL TIME SYSTEMS', 'INTERNAL': '25', 'EXTERNAL': '34', 'TOTAL': '59', 'GRADE': 'B', 'CREDIT': '3'}, {'SUB_CODE': '138FH', 'SUB_NAME': 'WEB SERVICES AND SERVICE ORIENTED ARCHITECTURE', 'INTERNAL': '24', 'EXTERNAL': '39', 'TOTAL': '63', 'GRADE': 'B+', 'CREDIT': '3'}, {'SUB_CODE': '138GY', 'SUB_NAME': 'SENSORS AND TRANSDUCERS', 'INTERNAL': '25', 'EXTERNAL': '31', 'TOTAL': '56', 'GRADE': 'B', 'CREDIT': '3'}], 'sgpa': 8.62}

**Comment by pacsui** [comment]
Oh no 
I didnt know roll numbers extended past 559 I just thought the next possible number would be 560 cause that's how our roll numbers are present and yeah that's what the roll number validator is checking for  lemme update the thing 
thanks @Akshay-shiva

**Comment by pacsui** [comment]
I just fixed it and it seems to work now 

![image](https://user-images.githubusercontent.com/37984032/129237786-72567123-7b09-474a-a137-9f5a109151b2.png)

check the new commit :)

**Comment by Akshay-shiva** [comment]
Done and dusted!
Great Job Bro
